project:
  type: website

website:
  title: "Martin S Andersen"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Research.qmd
      - Teaching.qmd
    tools: 
      - icon: twitter-x
        href: https://x.com/andersen_hecon
      - icon: github
        href: https://github.com/andersen-hecon
  twitter-card: true
  open-graph: true
  google-analytics: UA-34774254-1


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

