project:
  type: website

website:
  title: "Martin S Andersen"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Research.qmd
      - Teaching.qmd
    tools: 
      - icon: twitter
        href: https://x.com/andersen_hecon

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

